services:

  db:
    image: 'postgres:14-alpine'
    container_name: db
    restart: always
    environment:
      - POSTGRES_DB=serves_app
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
    ports:
      - "5555:5432"